# Kibana + ElasticSearch
# Access via "http://localhost:5601"

version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    networks: 
      - elastic
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    networks: 
      - elastic
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

networks: 
  elastic:
    driver: bridge